In [1]:
import numpy as np
import matplotlib as plt

y = [1,2,3]
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)

# Length of matrix (normalization)
np.linalg.norm(matrix)



[[1 2 3]
 [4 5 6]]


9.539392014169456

In [2]:
A = np.matrix([[1,2], [3,4]])
print(A.shape)
print(A.T)

identity = np.identity(3)
print(identity)

(2, 2)
[[1 3]
 [2 4]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
